// One fetcher per data source in the brief. Every fetcher returns
// { source, title, url, date, snippet }[] and never throws — a dead feed
// or a Firecrawl miss should shrink today's candidate pool, not kill the run.
// generate.mjs calls fetchAll() and logs whatever failed.
import { readFile, readdir } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import Parser from "rss-parser";

const rss = new Parser({ timeout: 15000 });

async function safeRSS(url, source, limit = 8) {
  try {
    const feed = await rss.parseURL(url);
    return (feed.items || []).slice(0, limit).map((it) => ({
      source,
      title: it.title?.trim() || "",
      url: it.link || "",
      date: it.isoDate || it.pubDate || null,
      snippet: (it.contentSnippet || it.content || "").slice(0, 280),
    }));
  } catch (err) {
    console.error(`[${source}] RSS fetch failed:`, err.message || err);
    return [];
  }
}

// ── Feeds that publish a real, public RSS/XML endpoint ──
export const fetchMortgageNewsDaily = () => safeRSS("https://www.mortgagenewsdaily.com/rss/full", "mortgage-news-daily");
export const fetchInman = () => safeRSS("https://www.inman.com/feed/", "inman");
export const fetchBiggerPockets = () => safeRSS("https://www.biggerpockets.com/blog/feed", "biggerpockets");

/**
 * Census Bureau Building Permits Survey — genuinely free and keyless for
 * low-volume use (a CENSUS_API_KEY just raises the rate limit). One data
 * point per run: latest national permits figure, framed as a housing-supply
 * signal for the Investor Edge / Market Pulse days.
 */
export async function fetchCensusPermits() {
  try {
    const key = process.env.CENSUS_API_KEY ? `&key=${process.env.CENSUS_API_KEY}` : "";
    const url = `https://api.census.gov/data/timeseries/eits/bps?get=cell_value,data_type_code,time_slot_id&for=us:*&time=from+2024${key}`;
    const res = await fetch(url, { signal: AbortSignal.timeout(15000) });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const rows = await res.json();
    const [header, ...data] = rows;
    const idx = Object.fromEntries(header.map((h, i) => [h, i]));
    const latest = data.at(-1);
    if (!latest) return [];
    return [
      {
        source: "census",
        title: `New residential building permits (units, national): ${latest[idx.cell_value]}`,
        url: "https://www.census.gov/construction/bps/",
        date: new Date().toISOString(),
        snippet: `Census Bureau Building Permits Survey, series ${latest[idx.data_type_code] || ""}.`,
      },
    ];
  } catch (err) {
    console.error("[census] fetch failed:", err.message || err);
    return [];
  }
}

/**
 * MLS Data Feeds — a raw multi-metro MLS feed needs broker-level CRMLS
 * credentials this pipeline doesn't have. Rather than fabricate an API,
 * reuse the site's own local-market data: the weekly Firecrawl-sourced
 * community pulse already generated by scripts/market-pulse and served at
 * web/public/data/market-pulse-<slug>.json. That *is* this brand's local
 * MLS-adjacent signal — new development, permitting, and price-relevant
 * local news for the exact zips Kareem serves.
 */
export async function fetchLocalMarketPulse() {
  try {
    const dataDir = path.resolve(fileURLToPath(import.meta.url), "../../../web/public/data");
    const files = await readdir(dataDir);
    const pulseFiles = files.filter((f) => f.startsWith("market-pulse-") && f.endsWith(".json"));
    const items = [];
    for (const file of pulseFiles) {
      const raw = JSON.parse(await readFile(path.join(dataDir, file), "utf8"));
      for (const it of raw.items || []) {
        items.push({ source: "mls", title: `${raw.place}: ${it.title}`, url: it.url, date: it.date || raw.generatedAt, snippet: "" });
      }
    }
    return items;
  } catch (err) {
    console.error("[mls/local-pulse] read failed:", err.message || err);
    return [];
  }
}

/**
 * Sources with no public API or reliable RSS — Zillow Research commentary,
 * Redfin's Data Center, the current NAR headline report, Google Trends'
 * trending real-estate queries, and top pain-point threads from the three
 * subreddits. Firecrawl search covers all five the same way market-pulse
 * already uses it for local news, so one API key does double duty.
 */
async function firecrawlSearch(client, query, source, { limit = 5, sources = ["news", "web"] } = {}) {
  try {
    const result = await client.search(query, { sources, limit, tbs: "qdr:d" }); // qdr:d = past 24h
    const hits = result.news?.length ? result.news : result.web || [];
    return hits.map((h) => ({ source, title: h.title?.trim() || "", url: h.url, date: h.date || null, snippet: (h.description || "").slice(0, 280) }));
  } catch (err) {
    console.error(`[${source}] Firecrawl search failed:`, err.message || err);
    return [];
  }
}

export const fetchZillowResearch = (client) =>
  firecrawlSearch(client, "Zillow median home price days on market inventory report", "zillow");

export const fetchRedfinDataCenter = (client) =>
  firecrawlSearch(client, "Redfin Data Center housing demand migration competitiveness report", "redfin");

export const fetchNAR = (client) =>
  firecrawlSearch(client, "National Association of Realtors existing home sales affordability index report", "nar");

export const fetchFedRates = (client) =>
  firecrawlSearch(client, "Federal Reserve mortgage rate decision 30-year 15-year today", "fed");

export const fetchGoogleTrends = (client) =>
  firecrawlSearch(client, "trending real estate search terms Google Trends how to buy a house", "google-trends", { sources: ["web"] });

export const fetchReddit = (client) =>
  firecrawlSearch(
    client,
    "site:reddit.com (r/RealEstate OR r/FirstTimeHomeBuyer OR r/realestateinvesting) top question",
    "reddit",
    { sources: ["web"] }
  );

/** Runs every fetcher, tolerating individual failures, and flattens the results. */
export async function fetchAll(firecrawlClient) {
  const [rssResults, censusResults, mlsResults, fcResults] = await Promise.all([
    Promise.all([fetchMortgageNewsDaily(), fetchInman(), fetchBiggerPockets()]),
    fetchCensusPermits(),
    fetchLocalMarketPulse(),
    Promise.all([
      fetchZillowResearch(firecrawlClient),
      fetchRedfinDataCenter(firecrawlClient),
      fetchNAR(firecrawlClient),
      fetchFedRates(firecrawlClient),
      fetchGoogleTrends(firecrawlClient),
      fetchReddit(firecrawlClient),
    ]),
  ]);
  return [...rssResults.flat(), ...censusResults, ...mlsResults, ...fcResults.flat()];
}
