"""
Realistic mock leads for testing without any API keys.
All businesses are fictional but match the target profile:
  - San Fernando Valley area
  - 5+ years in business
  - <50 reviews, 4.0+ rating
  - No website or outdated pre-2015 site
"""

AGENCY_MOCK_LEADS = [
    {
        "id": "mock_001",
        "place_id": "ChIJmock001",
        "name": "Mike Kowalski Home Inspections",
        "niche": "home_inspector",
        "city": "Woodland Hills",
        "address": "21300 Victory Blvd, Woodland Hills, CA 91364",
        "phone": "(818) 555-0101",
        "email": "mike@mkhi.example.com",
        "website": "",
        "website_status": "none",
        "rating": 4.8,
        "review_count": 18,
        "years_open": 9,
        "instagram": "mkhomeInspect",
        "linkedin": "",
        "scouted_at": "2026-05-07T09:00:00",
        "scouted_date": "2026-05-07",
    },
    {
        "id": "mock_002",
        "place_id": "ChIJmock002",
        "name": "Valley Pro Staging",
        "niche": "home_stager",
        "city": "Calabasas",
        "address": "4789 Commons Way, Calabasas, CA 91302",
        "phone": "(818) 555-0202",
        "email": "hello@valleyprostaging.example.com",
        "website": "http://valleyprostaging.example.com",
        "website_status": "outdated",
        "rating": 4.9,
        "review_count": 31,
        "years_open": 7,
        "instagram": "valleyprostaging",
        "linkedin": "",
        "scouted_at": "2026-05-07T09:01:00",
        "scouted_date": "2026-05-07",
    },
    {
        "id": "mock_003",
        "place_id": "ChIJmock003",
        "name": "Reyes General Contracting",
        "niche": "general_contractor",
        "city": "Tarzana",
        "address": "5600 Reseda Blvd, Tarzana, CA 91356",
        "phone": "(818) 555-0303",
        "email": "",
        "website": "",
        "website_status": "none",
        "rating": 4.9,
        "review_count": 12,
        "years_open": 11,
        "instagram": "",
        "linkedin": "",
        "scouted_at": "2026-05-07T09:02:00",
        "scouted_date": "2026-05-07",
    },
    {
        "id": "mock_004",
        "place_id": "ChIJmock004",
        "name": "SFV Moving Co",
        "niche": "moving_company",
        "city": "Encino",
        "address": "16500 Ventura Blvd, Encino, CA 91436",
        "phone": "(818) 555-0404",
        "email": "bookings@sfvmoving.example.com",
        "website": "http://sfvmoving.example.com",
        "website_status": "outdated",
        "rating": 4.6,
        "review_count": 28,
        "years_open": 8,
        "instagram": "",
        "linkedin": "",
        "scouted_at": "2026-05-07T09:03:00",
        "scouted_date": "2026-05-07",
    },
    {
        "id": "mock_005",
        "place_id": "ChIJmock005",
        "name": "Highlands Mortgage Group",
        "niche": "mortgage_broker",
        "city": "Woodland Hills",
        "address": "21031 Ventura Blvd, Woodland Hills, CA 91364",
        "phone": "(818) 555-0505",
        "email": "loans@highlandsmortgage.example.com",
        "website": "",
        "website_status": "none",
        "rating": 4.7,
        "review_count": 15,
        "years_open": 12,
        "instagram": "",
        "linkedin": "highlandsmortgagegroup",
        "scouted_at": "2026-05-07T09:04:00",
        "scouted_date": "2026-05-07",
    },
    {
        "id": "mock_006",
        "place_id": "ChIJmock006",
        "name": "Greenwood Property Management",
        "niche": "property_manager",
        "city": "Sherman Oaks",
        "address": "14724 Ventura Blvd, Sherman Oaks, CA 91403",
        "phone": "(818) 555-0606",
        "email": "info@greenwoodpm.example.com",
        "website": "",
        "website_status": "none",
        "rating": 4.5,
        "review_count": 9,
        "years_open": 6,
        "instagram": "",
        "linkedin": "greenwoodpm",
        "scouted_at": "2026-05-07T09:05:00",
        "scouted_date": "2026-05-07",
    },
    {
        "id": "mock_007",
        "place_id": "ChIJmock007",
        "name": "Carla Rios Real Estate Photography",
        "niche": "real_estate_photographer",
        "city": "Calabasas",
        "address": "23505 Calabasas Rd, Calabasas, CA 91302",
        "phone": "(818) 555-0707",
        "email": "",
        "website": "",
        "website_status": "none",
        "rating": 5.0,
        "review_count": 7,
        "years_open": 5,
        "instagram": "carlarios.photo",
        "linkedin": "",
        "scouted_at": "2026-05-07T09:06:00",
        "scouted_date": "2026-05-07",
    },
    {
        "id": "mock_008",
        "place_id": "ChIJmock008",
        "name": "Pacific Title & Escrow",
        "niche": "title_company",
        "city": "Thousand Oaks",
        "address": "3625 E Thousand Oaks Blvd, Thousand Oaks, CA 91362",
        "phone": "(805) 555-0808",
        "email": "orders@pacifictitle.example.com",
        "website": "http://pacifictitle.example.com",
        "website_status": "outdated",
        "rating": 4.7,
        "review_count": 22,
        "years_open": 14,
        "instagram": "",
        "linkedin": "pacific-title-escrow",
        "scouted_at": "2026-05-07T09:07:00",
        "scouted_date": "2026-05-07",
    },
]


KAREEM_MOCK_LEADS = [
    {
        "id": "kmock_001",
        "source": "expired_listing",
        "type": "seller",
        "name": "Rodriguez",
        "address": "23847 Califa St",
        "city": "Woodland Hills",
        "zip": "91364",
        "phone": "(818) 555-1001",
        "email": "mrodriguez@example.com",
        "list_price": 895000,
        "days_on_market": 47,
        "expired_date": "2026-04-20",
        "bedrooms": 4,
        "bathrooms": 3,
        "sqft": 2100,
        "motivation_score": 85,
        "avm": 920000,
        "scouted_date": "2026-05-07",
    },
    {
        "id": "kmock_002",
        "source": "fsbo",
        "type": "seller",
        "name": "Patel",
        "address": "4912 Canoga Ave",
        "city": "Woodland Hills",
        "zip": "91364",
        "phone": "(818) 555-1002",
        "email": "spatel@example.com",
        "list_price": 1150000,
        "bedrooms": 5,
        "bathrooms": 4,
        "sqft": 2850,
        "zillow_url": "https://zillow.com/example",
        "motivation_score": 70,
        "avm": 1180000,
        "scouted_date": "2026-05-07",
    },
    {
        "id": "kmock_003",
        "source": "pre_foreclosure",
        "type": "seller",
        "name": "Williams",
        "address": "19845 Sherman Way",
        "city": "Tarzana",
        "zip": "91356",
        "phone": "(818) 555-1003",
        "email": "",
        "avm": 780000,
        "equity_pct": 42,
        "nod_date": "2026-03-15",
        "motivation_score": 95,
        "scouted_date": "2026-05-07",
    },
    {
        "id": "kmock_004",
        "source": "absentee_owner",
        "type": "seller",
        "name": "Chen",
        "address": "16742 Oxnard St",
        "city": "Encino",
        "zip": "91316",
        "phone": "",
        "email": "jchen.invest@example.com",
        "avm": 1320000,
        "equity_pct": 67,
        "owner_state": "TX",
        "motivation_score": 60,
        "scouted_date": "2026-05-07",
    },
    {
        "id": "kmock_005",
        "source": "expired_listing",
        "type": "seller",
        "name": "Thompson",
        "address": "9203 De Soto Ave",
        "city": "Chatsworth",
        "zip": "91311",
        "phone": "(818) 555-1005",
        "email": "bthompson@example.com",
        "list_price": 720000,
        "days_on_market": 33,
        "expired_date": "2026-04-28",
        "bedrooms": 3,
        "bathrooms": 2,
        "sqft": 1650,
        "motivation_score": 85,
        "avm": 745000,
        "scouted_date": "2026-05-07",
    },
]
